#!/bin/sh

case "$1" in
	start)
		[ "${SF2000_HEARTBEAT:-1}" = 0 ] && exit 0
		echo "Starting sf2000-heartbeat: "
		/usr/sbin/sf2000-heartbeat &
		echo "OK"
		;;
	stop)
		killall sf2000-heartbeat 2>/dev/null || true
		;;
esac
